### ISSUE TITLE
Existing DB page with empty Title creates error.

### ISSUE THREAD

**Issue by tarihala** [Rujuu-prog/markdown2notion#5]
## Summary

When the database already contains a page with no text in the Title column (first column), it produces a error `Cannot read properties of undefined (reading 'text')` and the operation fails.

## Steps to Reproduce
1. Create database. Add one entry with no text in the Name column
2. Follow example in README for "markdownToNotion()", setting up `index.ts` with tokens and database id and run (`node index.ts`).
3. Error will occur - `Cannot read properties of undefined (reading 'text')`

## Expected Behavior
Throw a helpful error (e.g. "Existing page without text in Title column") or directly archive the page.

## Actual Behavior
Throws the error `Cannot read properties of undefined (reading 'text')` and does not proceed. User is unaware why it has not worked.

## Environment
npm version: 10.7.0
`markdown2notion`: 1.1.0

## Suggested fix:
Traced the issue to `src/markdownToNotion.ts`, line 72. 
https://github.com/Rujuu-prog/markdown2notion/blob/3af8ebbc71d35ecbda9de3782fe60ff42ec8246c/src/markdownToNotion.ts#L72
Can simply add something like this, if one simply wants to raise the error and let the user decide what to do:
```typescript
existingPages.results.forEach((page) => {
    if (page.properties.Title.title.length != 0) {
        existingPageTitles[page.id] = page.properties.Title.title[0].text.content;
        } else {
            throw new Error('Existing pages in DB without text in the "title" column.');
        }
    });
    return existingPageTitles;
```

P.S Thanks for sharing your work Rujuu-prog!

**Comment by Rujuu-prog** [comment]
@tarihala 
Thank you for creating the issue.
I really appreciate you outlining your proposed fix.

I will try both approaches — throwing an error and directly archiving — and implement whichever works better.
I'll aim to release this fix as soon as possible.

I hope you'll continue using the product in the future!

**Comment by tarihala** [comment]
Thanks @Rujuu-prog!

**Comment by Rujuu-prog** [comment]
@tarihala 
Thank you again for reporting the bug!
In version v1.2.0, I have fixed the issue as described below, and I hope you continue to use this module.
If you find any other bugs or have a better suggestion for this fix, please let me know! 🤝
---
I have modified the code so that if a page has an empty title, it will be archived, and a warning saying 
"Page with ID ${page.id} has an empty title. Archiving the page." 
will be output.
---
Thank you!

**Comment by tarihala** [comment]
Nice! Glad I could help. And thanks again for sharing this tool.
